#!/usr/bin/env python
# -*- coding: utf-8 -*-

#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
from datetime import datetime, timedelta

args = sys.argv[1:]

if args[0] == 'buoys_es':
    from oceanoobsbrasil.buoys.es import ESBuoy
    ESBuoy().get()

if args[0] == 'buoys_pe':
    from oceanoobsbrasil.buoys.pe import PEBuoy
    PEBuoy().get()

if args[0] == 'buoys_pnboia':
    from oceanoobsbrasil.buoys.pnboia import Pnboia
    Pnboia().get()

if args[0] == 'buoys_se':
    from oceanoobsbrasil.buoys.se import SEBuoy
    SEBuoy().get()

if args[0] == 'buoys_simcosta':
    from oceanoobsbrasil.buoys.simcosta import Simcosta
    Simcosta().get()

if args[0] == 'observational_data_ricosurf':
    from oceanoobsbrasil.observational_data.ricosurf import RicoSurf
    RicoSurf().get()

if args[0] == 'observational_data_wavecheck':
    from oceanoobsbrasil.observational_data.wavecheck import Wave
    Wave().get()

if args[0] == 'others_clean_beach':
    from oceanoobsbrasil.others.clean_beach import CleanBeach
    CleanBeach().get()

if args[0] == 'others_ndbc':
    from oceanoobsbrasil.others.ndbc import Ndbc
    Ndbc().get()

if args[0] == 'remote_sensing_altimeter_download':
    from oceanoobsbrasil.remote_sensing.altimeter import Altimeter
    Altimeter().download_ftplib_nodc()

if args[0] == 'remote_sensing_altimeter':
    from oceanoobsbrasil.remote_sensing.altimeter import Altimeter
    Altimeter().get()


if args[0] == 'remote_sensing_scatterometer':
    from oceanoobsbrasil.remote_sensing.scatterometer import Metop
    Metop().get()

if args[0] == 'remote_sensing_scatterometer_download':
    from oceanoobsbrasil.remote_sensing.scatterometer import Metop
    Metop().download()

if args[0] == 'remote_sensing_sst':
    from oceanoobsbrasil.remote_sensing.sst import Mur
    Mur().get()

if args[0] == 'tides_epagri':
    from oceanoobsbrasil.tides.epagri import EpagriTide
    EpagriTide().get()

if args[0] == 'tides_ilha_fiscal_tide':
    from oceanoobsbrasil.tides.ilha_fiscal_tide import IlhaFiscal
    IlhaFiscal().get()

if args[0] == 'tides_santos_tide':
    from oceanoobsbrasil.tides.santos_tide import TideSantos
    TideSantos().get()

if args[0] == 'tides_simcosta':
    from oceanoobsbrasil.tides.simcosta import SimcostaTide
    SimcostaTide().get()

if args[0] == 'weather_stations_inmet':
    from oceanoobsbrasil.weather_stations.inmet import Inmet
    Inmet().get()

if args[0] == 'weather_stations_metar':
    from oceanoobsbrasil.weather_stations.metar import Metar
    Metar().get()

if args[0] == 'weather_stations_wind_guru':
    from oceanoobsbrasil.weather_stations.wind_guru import WindGuru
    WindGuru().get()


if args[0] == 'delete_old_stations':
    from oceanoobsbrasil.db import GetData
    date_time = (datetime.utcnow() - timedelta(days=5)).strftime("%Y-%m-%d")

    GetData().delete(table='data_stations', date_time=['<=', date_time])

if args[0] == 'delete_old_no_stations':
    from oceanoobsbrasil.db import GetData
    date_time = (datetime.utcnow() - timedelta(days=5)).strftime("%Y-%m-%d")
    GetData().delete(table='data_no_stations', date_time=['<=', date_time])
